recon_params.NUM_LEVELS = 3;
recon_params.NB_SIZES = [9 9 5];
recon_params.FULL_RECON_SIZE = [100 100 100];
load('../../data/tubes_exemplars.mat');  
recon_params.EXEMPLARS = E(1:3);
recon_params.NB_INDICES = 1:3;
recon_params.NUM_CORES = 4;
recon_params.ANN_ALGO = 'FLANN';
recon_params.UseNeighborhoodSearchWeights = false;
ReconH = SetupReconMultiRes(recon_params);
[S_star, Recon] = Reconstruct(ReconH, [5, 25, 50]);
DestroyReconMultiRes(Recon);
